"""
Build RAG index for Cloudflare Worker from knowledge base
Converts knowledge_base.json to rag_index.json format
"""
import json
import os

def chunk_text(text: str, max_chars: int = 800) -> list[str]:
    """Split text into chunks"""
    if len(text) <= max_chars:
        return [text]
    
    chunks = []
    paragraphs = text.split('\n\n')
    current_chunk = ""
    
    for para in paragraphs:
        if len(current_chunk) + len(para) + 2 <= max_chars:
            current_chunk += para + "\n\n"
        else:
            if current_chunk:
                chunks.append(current_chunk.strip())
            current_chunk = para + "\n\n"
    
    if current_chunk:
        chunks.append(current_chunk.strip())
    
    return chunks

def build_rag_index():
    """Build RAG index from knowledge base"""
    print("Building RAG index for Cloudflare Worker...")
    
    # Load knowledge base
    with open('knowledge_base.json', 'r', encoding='utf-8') as f:
        knowledge = json.load(f)
    
    rag_chunks = []
    site_url = os.getenv('PUBLIC_SITE_URL', 'http://localhost:8080')
    
    for entry in knowledge:
        title = entry.get('title', 'Thrive Wellness')
        content = entry.get('content', '')
        
        # Determine URL based on title
        url = f"{site_url}/"
        if 'product' in title.lower() or 'bundle' in title.lower():
            url = f"{site_url}/shop"
        elif 'team' in title.lower() or 'leadership' in title.lower():
            url = f"{site_url}/team"
        elif 'contact' in title.lower():
            url = f"{site_url}/contact"
        elif 'shipping' in title.lower():
            url = f"{site_url}/shipping"
        elif 'faq' in title.lower():
            url = f"{site_url}/faq"
        elif 'company' in title.lower() or 'mission' in title.lower():
            url = f"{site_url}/about"
        
        # Split content into chunks
        text_chunks = chunk_text(content)
        
        for i, chunk in enumerate(text_chunks):
            chunk_title = title if len(text_chunks) == 1 else f"{title} (Part {i+1})"
            rag_chunks.append({
                "title": chunk_title,
                "url": url,
                "content": chunk.strip(),
                "embedding": []  # Embeddings will be generated by Cloudflare Worker
            })
    
    # Build index
    rag_index = {
        "chunks": rag_chunks
    }
    
    # Save to public folder for Cloudflare Pages
    output_path = '../public/rag_index.json'
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(rag_index, f, indent=2, ensure_ascii=False)
    
    print(f"\n✅ RAG index built successfully!")
    print(f"   Total chunks: {len(rag_chunks)}")
    print(f"   Output: {output_path}")
    print(f"\n🚀 Ready for Cloudflare Pages deployment!")

if __name__ == "__main__":
    build_rag_index()
